version: '2'

networks:
  devops:
    driver: bridge

services:
  jenkins:
    image: jenkins
    networks:
      - devops
    ports:
      - "49001:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
    depends_on:
      - sonar

  sonar:
    image: sonarqube
    ports: 
      - "49002:9000"
      - "5432:5432"
    networks:
      - devops
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
  sonardb:
    image: postgres
    networks:
      - devops
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
